/*
Magnitude Analysis

Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
*/

-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;
/*
country	        total_customers
United States	7482
Australia	    3591
United Kingdom	1913
France	        1810
Germany	        1780
Canada	        1571
n/a	            337
*/

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;
/*
gender	total_customers
Male	9341
Female	9128
n/a	    15
*/

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;
/*
category	total_products
Components	127
Bikes	    97
Clothing	35
Accessories	29
NULL	    7
*/

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;
/*
category	avg_cost
Bikes	    949
Components	264
NULL	    28
Clothing	24
Accessories	13
*/

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
/*
category	total_revenue
Bikes	    28316272
Accessories	700262
Clothing	339716
*/

-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;
/*
customer_key	first_name	last_name	total_revenue
1133	        Kaitlyn	    Henderson	13294
1302	        Nichole	    Nara	    13294
1309	        Margaret	He	        13268
1132	        Randall	    Dominguez	13265
1301	        Adriana	    Gonzalez	13242
*/

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
/*
country	        total_sold_items
United States	20481
Australia	    13346
Canada	        7630
United Kingdom	6910
Germany	        5626
France	        5559
n/a	            871
*/